#! /bin/bash
#
# simple init script for xervphite
#
#
# chkconfig: 345 99 01
# description: xervphite nagios -> graphite script
#
# File : xervphite

prog="###ROOT###/bin/xervphite.py --config=###ROOT###/etc/xervphite/xervphite.ini"
RETVAL=0

start () {
        echo -n "Starting Xervphite..."
        $prog &
        RETVAL=$?
        if [ $RETVAL -eq 0 ] 
        then
            echo "OK"
        else
            echo "FAILED"
        fi
}

stop () {
        echo -n "Stopping Xervphite..."
        if [ -a cat ###ROOT###/tmp/xervphite.pid ]
        then
            kill `cat ###ROOT###/tmp/xervphite.pid`
            RETVAL=$?
            if [ $RETVAL -eq 0 ]
            then
                if [ -a ###ROOT###/tmp/xervphite.pid ]
                then
                    rm ###ROOT###/tmp/xervphite.pid
                fi
                echo "OK"
            else
                echo "FAILED"
            fi
        else
            echo "WARNING (NO PID FILE FOUND)"
        fi
}

restart () {
        stop
        start
}


# See how we are called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  status)
        status $prog
        RETVAL=$?
        ;;
  *)
        echo "Usage: service xervphite {start|stop|restart|reload}"
        RETVAL=2
        ;;
esac

exit $RETVAL
